#:import system platform.system
<DashBoard>:
	FloatLayout:

		MDRectangleFlatIconButton:
			id: DashBtn
			icon: "led-off"
		    text: "Hi..."
		    width: dp(150)
		    halign: 'center'
		    pos_hint: {"center_x": .5, "center_y": .5}

		MDLabel:
			id: platform_name
			pos_hint: {"center_x": .5, "center_y": .4}
			size_hint: (0.4, 0.1)
			halign: "center"
			font_style: "Caption"
			text: "Platform: %s" % system()
			theme_text_color: "Custom"
			text_color: rgba('#568A2F')


